## 45장: 프로미스

---

### **45.1 비동기 처리를 위한 콜백 패턴의 단점**

### 45.1.1 콜백 헬

```jsx
// GET 요청 비동기 함수
const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status == 200) {
      console.log(JSON.parse(xhr.response));
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

// id가 1인 nag를 취득
get("https://jansorry.안알려줌/api/v1/nags/1");
/*
{
  "id": 1,
  "content": "대학은 어디 갈거니?",
  "price": 50000
}
*/
```

`get` 함수가 서버의 응답 결과를 반환하려면 어떻게 해야할까?

`get` 함수는 비동기 함수다.  
**비동기 함수를 호출하면 함수 내부의 비동기 코드가 완료되지 않아도 기다리지 않고 즉시 종료된다.**  
**즉, 비동기 함수 내부의 비동기 코드는 비동기 함수가 종료된 이후 완료된다.**  
**따라서 비동기 함수 내부의 비동기 코드에서 처리 결과를 외부로 반환, 상위 스코프 변수 할당은 기대한대로 동작하지 않는다.**

```jsx
let g = 0;

// 비동기 함수 setTimeout 함수는 콜백 함수의 결과를 외부 반환/상위 스코프 변수 할당하지 못한다.
setTimeout(() => {
  g = 100;
}, 0);
console.log(g); // 0
```

`get` 함수는 `onload` **이벤트 핸들러가 비동기로 동작**하기 때문에 비동기 함수다.

`get` 함수를 호출하면 GET 요청을 전송, `onload` 이벤트 핸들러 등록 후 `undefined`를 반환하고 즉시 종료된다.

```jsx
let nags;

// get 함수가 서버의 응답 결과를 반환하도록 수정
const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status == 200) {
      // 1. 상위 스코프의 변수에 할당
      nags = JSON.parse(xhr.response);

      // 2. 응답을 반환
      return JSON.parse(xhr.response);
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

// id가 1인 nag를 취득
const response = get("https://jansorry.안알려줌/api/v1/nags/1");
console.log(response); // undefined
```

`get` 함수의 호출 후 실행 동작

1. `XMLHttpRequest` 객체 생성
2. HTTP 요청 초기화, HTTP 요청 전송
3. `xhr.onload` 이벤트 핸들러 프로퍼티에 이벤트 핸들러 바인딩 후 종료

**1. 상위 스코프 변수에 할당의 경우**

`onload` 이벤트 핸들러에 바인딩한 이벤트 핸들러는 맨 마지막 코드의 `console.log`가 종료한 이후 호출된다.  
`console.log`가 실행되는 시점은 서버의 응답 결과가 할당되기 이전이다.

즉, 위 코드의 1번 상위 스코프 변수 할당의 경우 처리 순서가 보장되지 않아 의도대로 동작하지 않는다.

이유는 아래에 자세히 서술

**2. 반환문을 작성한 경우**

`onload` 이벤트 핸들러에 바인딩한 반환문은 `get` 함수의 반환문이 아니다.  
`get` 함수는 반환문이 생략, `undefined`를 반환한다.

즉, 위 코드의 2번 `return`의 경우 `onload` 이벤트 핸들러의 반환값을 캐치할 수 없기 때문에 의도대로 동작하지 않는다.

<br>

**1-2. 상위 스코프 변수 할당에서 처리 순서가 보장되지 않는 이유**

`get` 호출 -> `get` 함수의 실행 컨텍스트가 생성되어 콜 스택에 푸시된다. 이후 코드가 실행될 때 `xhr.onload` 이벤트 핸들러 프로퍼티에 이벤트 핸들러가 바인딩된다.

`get` 함수 종료 -> `get` 함수의 실행 컨텍스트가 콜스택에서 팝, 코드 맨 마지막의 `console.log` 호출 -> `console.log`의 실행 컨텍스트가 콜 스택에 푸시

서버 응답 도착 -> `load` 이벤트 발생 -> **태스크 큐에 저장되어 대기** -> **콜 스택이 비면 이벤트 루프에 의해 콜 스택으로 푸시, 실행**

즉, `xhr.onload` 이벤트 핸들러가 실행될 때는 콜 스택이 빈 상태여야 하므로 `console.log`는 종료된 이후이기 때문에 `undefined`가 출력된다.

### 결론

**비동기 함수는 비동기 처리 결과를 외부 반환할 수 없고, 상위 스코프 변수 할당도 불가능하다.  
따라서 해당 후속 처리는 비동기 함수 내부에서 수행해야 한다.  
이를 범용적으로 사용하기 위해 일반적으로 콜백 함수를 전달한다.**

```jsx
const get = (url, success, failure) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status == 200) {
      // 응답을 콜백 함수에 전달, 호출
      success(JSON.parse(xhr.response));
    } else {
      // 에러 정보를 인수로 전달
      failure(xhr.status);
    }
  };
};

// id가 1인 nag를 취득
// 응답의 후속 처리를 위한 콜백 함수를 전달
get("https://jansorry.안알려줌/api/v1/nags/1", console.log, console.error);
/*
{
  "id": 1,
  "content": "대학은 어디 갈거니?",
  "price": 50000
}
*/
```

후속 처리를 수행하는 비동기 함수가 처리 결과를 갖고 또 비동기 함수를 호출해야 한다면, 콜백 함수의 호출이 중첩되어 복잡해진다.

이를 **콜백 헬<sup>callback hell</sup>** 이라 한다.

```jsx
const get = (url, callback) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status == 200) {
      // 응답을 콜백 함수에 전달, 호출
      success(JSON.parse(xhr.response));
    } else {
      console.error(`...`);
    }
  };
};

const url = `https://jansorry.안알려줌/api/v1`;

get(`${url}/nags`, ({ id }) => {
  console.log(id); // 1
  get(`${url}/nags/${id}`, (nag) => {
    console.log(nag); // {id: 1, content: '잔소리잔소리', ...}
  });
});
```

위 예제는 `GET` 요청의 응답을 취득하여 또 다시 `GET` 요청을 한다. 해당 요청이 길어지면 아래처럼 가독성을 해치며 실수를 유발한다.

```jsx
get(`/step1`, (a) => {
  get(`/step2/${a}`, (b) => {
    get(`/step3/${b}`, (c) => {
      get(`/setp4/${c}`, (d) => {
        console.log(d);
      });
    });
  });
});
```

<br>

### 45.1.2 에러 처리의 한계

콜백 패턴에서 가장 심각한 문제는 에러 처리가 곤란하다는 것이다.

```jsx
try {
  setTimeout(() => {
    throw new Error("에러");
  }, 1000);
} catch (e) {
  // 에러 캐치가 불가능
  console.error(e);
}
```

1. 비동기 함수 `setTimeout`이 호출되면 실행 컨텍스트가 생성되어 콜 스택에 푸시, 실행된다.

2. `setTimeout`은 비동기 함수이므로 즉시 종료되어 콜 스택에서 제거된다.

3. 타이머가 만료되면 `setTimeout`의 콜백 함수가 태스크 큐로 푸시, 콜 스택이 비면 이벤트 루프에 의해 콜 스택으로 푸시, 실행된다.

`setTimeout`의 콜백 `throw new ...` 함수가 실행될 때 `setTimeout` 함수는 이미 콜 스택에서 제거되었다.

이는 콜백 `throw new ...` 함수를 호출한 것이 `setTimeout` 함수가 아니라는 것이다.

**에러는 호출자<sup>caller</sup> 방향으로 전파된다.**  
 => 콜 스택의 아래 방향으로 전파된다.  
 => 실행 중인 실행 컨텍스트가 푸시되기 직전에 푸시된 실행 컨텍스트 방향  
 => 콜백 함수를 호출한 호출자

그러나 콜백 `throw new ...` 함수를 호출한 것은 `setTimeout` 함수가 아니므로 `catch` 블록에서 캐치되지 않는다.

이를 극복하기 위해 ES6에서 **프로미스<sup>Promise</sup>** 가 도입되었다.

<br>

### **45.2 프로미스의 생성**

Promise 생성자 함수를 new 연산자와 함께 호출하면 프로미스(Promise 객체)를 생성한다. (표준 빌트인 객체)

Promise 생성자 함수는 비동기 처리를 수행할 콜백 함수 `resolve`, `reject`를 인수로 전달받는다.

```jsx
const promise = new Promise((resolve, reject) => {
  if (/* 비동기 처리 성공 */) {
    resolve('result');
  } else { // 비동기 처리 실패
    reject('failure reason');
  }
});
```

`get`을 프로미스를 사용해 다시 구현해 보자.

```jsx
const get = (url) => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open("GET", url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status == 200) {
        // 성공적으로 응답을 받으면 resolve
        resolve(JSON.parse(xhr.response));
      } else {
        // 에러 처리 reject
        reject(new Error(xhr.status));
      }
    };
  });
};

// get 함수는 프로미스를 반환한다.
get(`https://jansorry.안알려줌/api/v1/nags`);
```

| 프로미스의 상태<sup>state</sup> 정보 | 의미                                  | 상태 변경 조건                   |
| ------------------------------------ | ------------------------------------- | -------------------------------- |
| pending                              | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |
| fulfilled                            | 비동기 처리가 수행된 상태(성공)       | resolve 함수 호출                |
| rejected                             | 비동기 처리가 수행된 상태(실패)       | reject 함수 호출                 |

생성된 직후 프로미스는 `pending` 상태다.  
이후 비동기 처리 결과에 따라 프로미스의 상태가 변경된다.

- 비동기 처리 성공: `resolve` 호출, `fulfilled` 상태로 변경

- 비동기 처리 실패: `reject` 호출, `rejected` 상태로 변경

**프로미스의 상태는 resolve 또는 reject 함수를 호출하는 것으로 결정된다.**

<img width="1043" alt="image" src="https://github.com/beomxtone/study-js-deep-dive/assets/28244235/c9fe7d1b-4006-4347-a73c-967eb1b782ee">

`fulfilled` 또는 `rejected` 상태를 `settled` 상태라고 한다.

`settled` 상태가 되면 더는 다른 상태로 변화할 수 없다.

프로미스는 비동기 처리 상태와 비동기 처리 결과를 상태로 갖는다.

```jsx
const fulfilled = new Promise((resolve) => resolve(1));
```

<img width="692" alt="image" src="https://github.com/beomxtone/study-js-deep-dive/assets/28244235/0de2939d-944b-4845-828c-2c00062ecdfd">

**프로미스는 비동기 처리 상태와 처리 결과를 관리하는 객체다.**

<br>

### **45.3 프로미스의 후속 처리 메서드**

프로미스의 비동기 처리 상태가 변화하면 후속 처리를 해야 한다.

이를 위해 프로미스는 후속 메서드 `then`, `catch`, `finally`를 제공한다.

**프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출된다.**

후속 처리 메서드는 프로미스를 반환, 콜백 함수에 프로미스 처리 결과가 인수로 전달된다.

### 45.3.1 Promise.prototype.then

`then` 메서드는 두 개의 콜백 함수를 인수로 전달받는다.

- 첫 번째 콜백은 `fulfilled` 상태에 호출된다. (성공 처리)

- 두 번째 콜백은 `rejected` 상태에 호출된다. (실패 처리)

```jsx
// fulfilled
new Promise((resolve) => resolve("fulfilled")).then(
  (v) => console.log(v),
  (e) => console.error(e)
); // fulfilled

//rejected
new Promise((_, reject) => reject(new Error("rejected"))).then(
  (v) => console.log(v),
  (e) => console.error(e)
); // Error: rejected
```

`then` 메서드는 언제나 프로미스를 반환한다.

### 45.3.2 Promise.prototype.catch

`catch` 메서드는 한 개의 콜백 함수를 인수로 전달으며, 이 콜백은 프로미스가 `rejected` 상태인 경우만 호출된다.

```jsx
// rejected
new Promise((_, reject) => reject(new Error("rejected"))).catch((e) =>
  console.log(e)
); // Error: rejected
```

`catch`는 `then`과 동일하게 동작하므로 언제나 프로미스를 반환한다.

### 45.3.3 Promise.prototype.finally

`finally` 메서드는 한 개의 콜백 함수를 인수로 전달받으며, 콜백은 성공 실패와 상관없이 무조건 한 번 호출된다.

언제나 프로미스를 반환한다.

```jsx
const get = (url) => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open("GET", url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status == 200) {
        // 성공적으로 응답을 받으면 resolve
        resolve(JSON.parse(xhr.response));
      } else {
        // 에러 처리 reject
        reject(new Error(xhr.status));
      }
    };
  });
};

get(`https://jansorry.안알려줌/api/v1/nags`)
  .then((res) => console.log(res))
  .catch((err) => console.error(err))
  .finally(() => console.log("Bye!"));
```

### **45.4 프로미스의 에러 처리**

프로미스는 비동기 처리에서 발생한 에러를 `then` 메서드의 두 번째 콜백 함수로 처리할 수 있다.

또는 후속 처리 메서드 `catch`를 사용해도 가능하다.

```jsx
const wrongUrl = `어쩌고 저쩌고`;

// then의 두 번째 콜백
get(wrongUrl).then(
  (res) => console.log(res),
  (err) => console.error(err)
); // Error: 404

// catch
get(wrongUrl)
  .then((res) => console.log(res))
  .catch((err) => console.error(err)); // Error: 404

// catch는 내부적으로 다음과 같이 처리된다.
~~~
  .then(undefined, err => console.error(err)); // Error: 404
```

`catch` 메서드는 `then` 내부에서 발생한 에러 모두 캐치할 수 있고, 가독성 또한 좋으므로 오류 처리는 `catch`에서 하는 것을 권장한다.

<br>

### **45.5 프로미스 체이닝**

프로미스는 `then`, `catch`, `finally` 후속 처리 메서드를 통해 콜백 헬을 해결한다.

```jsx
const url = `https://jansorry.안알려줌/api/v1`;

get(`${url}/nags`)
  .then(({ id }) => get(`${url}/nags/${id}`))
  .then((nagInfo) => console.log(nagInfo))
  .catch((err) => console.error(err));
```

후속 처리 메서드는 언제나 프로미스를 반환하므로 연속적으로 호출할 수 있다.

이를 프로미스 체이닝<sup>promise chaining</sup>이라 한다.

후속 처리 메서드는 콜백함수가 반환한 프로미스를 반환하고, 만약 프로미스가 아닌 값을 반환하더라도 암묵적으로 `resolve` 혹은 `reject`하여 프로미스를 생성해 반환한다.

프로미스를 사용하면 콜백 헬이 발생하지는 않지만, 콜백 패턴을 사용하므로 가독성이 좋지 않다.

이는 ES8에서 도입된 `async`/`await`를 통해 해결할 수 있다.

```jsx
(async () => {
  const { id } = await get(`${url}/nags`);
  const nag = await get(`${url}/nags/${id}`);

  console.log(nag);
})();
```

`async`/`await`도 프로미스를 기반으로 동작한다.  
46.6절에서 자세히 알아보자.

<br>

### **45.6 프로미스의 정적 메서드**

Promise는 메서드를 가질 수 있으며, 5가지 정적 메서드를 제공한다.

### 45.6.1 Promise.resolve / Promise.reject

`resolve`와 `reject` 메서드는 이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용한다.

```jsx
const resolved = Promise.resolve([1, 2, 3]);
resolved.then(console.log); // [1, 2, 3]

// 다음과 같다.
const resolved = new Promise((resolve) => resolve([1, 2, 3]));
```

### 45.6.2 Promise.all

`Promise.all` 메서드는 여러 개의 비동기 처리를 모두 병렬<sup>parallel</sup> 처리할 때 사용한다.

```jsx
const reqData1 = () =>
  new Promise((resolve) => setTimeout(() => resolve(1), 3000));
const reqData2 = () =>
  new Promise((resolve) => setTimeout(() => resolve(2), 2000));
const reqData3 = () =>
  new Promise((resolve) => setTimeout(() => resolve(3), 1000));

// 세 개의 비동기 처리를 순차적 처리
const res = [];
reqData1()
  .then((data) => {
    res.push(data);
    return reqData2();
  })
  .then((data) => {
    res.push(data);
    return reqData3();
  })
  .then((data) => {
    res.push(data);
    console.log(res); // [1, 2, 3] => 약 6초 소요
  })
  .catch(console.error);

// Promise.all 사용
Promise.all([reqData1(), reqData2(), reqData3()])
  .then(console.log) // [1, 2, 3] => 약 3초 소요
  .catch(console.error);
```

`Promise.all` 메서드는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다.

전달받은 모든 프로미스가 모두 `fulfilled` 상태가 되면 모든 처리 결과를 배열에 저장해 새로운 프로미스를 반환한다.

각 프로미스는 다음과 같이 동작한다.

- 첫 번째 프로미스: 3초 후 1을 resolve
- 두 번째 프로미스: 2초 후 2를 resolve
- 세 번째 프로미스: 1초 후 3을 resolve

`Promise.all` 메서드는 인수로 받은 배열의 모든 프로미스가 모두 `fulfilled` 상태가 되면 종료한다.  
따라서 해당 메서드가 종료되는 시간은 가장 늦게 `fulfilled` 상태가 되는 프로미스의 처리 시간보다 조금 더 길다.

첫 번째 프로미스가 가장 나중에 `fulfilled` 상태가 되어도 첫 번째 프로미스가 `resolve`한 처리 결과부터 차례대로 배열에 저장해 `resolve`하는 새 프로미스를 반환한다.

**즉, 처리 순서가 보장된다.**

`Promise.all` 메서드는 프로미스가 하나라도 `rejected` 상태가 되면 나머지가 `fulfilled`되는 것을 기다리지 않고 즉시 종료한다.

### 45.6.3 Promise.race

`race` 메서드는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받아  
가장 먼저 `fulfilled` 상태가 된 프로미스의 처리 결과를 `resolve`하는 새 프로미스를 반환한다.

```jsx
Promise.race([
  new Promise((resolve) => setTimeout(() => resolve(1), 3000)), // 1
  new Promise((resolve) => setTimeout(() => resolve(2), 2000)), // 2
  new Promise((resolve) => setTimeout(() => resolve(3), 1000)), // 3
])
  .then(console.log) // 3
  .catch(console.log);
```

프로미스가 하나라도 `rejected` 상태가 되면 `all` 메서드처럼 에러를 `reject`하는 새로운 프로미스를 즉시 반환한다.

### 45.6.4 Promise.allSettled

`Promise.allSettled` 메서드도 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다.

전달받은 프로미스가 모두 `settled` 상태가 되면 처리 결과를 배열로 반환한다.

```jsx
Promise.allSettled([
  new Promise((resolve) => setTimeout(() => resolve(1), 2000)),
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error!")), 1000)
  ),
]).then(console.log);
/*
[
  {status: 'fulfilled', value: 1},
  {status: 'rejected', reason: Error ~~}
]
*/
```

해당 메서드가 반환한 배열에는 인수로 전달받은 모든 프로미스들의 처리 결과가 모두 담겨있다.

프로미스의 처리 결과를 나타내는 객체는 다음과 같다.

- `filfilled` : 비동기 처리 상태를 나타내는 `status` 프로퍼티와 처리 결과를 나타내는 `value` 프로퍼티를 갖음
- `rejected` : 비동기 처리 상태를 나타내는 `status` 프로퍼티와 에러를 나타내는 `reason` 프로퍼티를 갖음

<br>

### **45.7 마이크로태스크 큐**

```jsx
setTimeout(() => console.log(1), 0);

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3));
```

위의 코드는 1 -> 2 -> 3 순으로 출력될 것처럼 보이지만 2 -> 3 -> 1 순으로 출력된다.

이는 프로미스 후속 처리 메서드의 콜백 함수가 태스크 큐가 아니라 마이크로태스크 큐<sup>microtask queue/job queue</sup>에 저장되기 때문이다.

마이크로태스크 큐와 태스크 큐는 별도의 큐이며, 마이크로태스크 큐에는 프로미스의 후속 처리 메서드의 콜백 함수가 일시 저장된다.

**마이크로태스크 큐는 태스트큐보다 우선순위가 높다.**

<br>

### **45.8 fetch**

`fetch` 함수는 HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API다.

HTTP 요청을 전송할 URL, 요청 메서드, 요청 헤더, 페이로드 등을 설정한 객체를 전달한다.

**fetch 함수는 HTTP 응답을 나타내는 Response 객체를 래핑한 Promise 객체를 반환한다.**

이후 후속 처리 메서드 `then`을 통해 프로미스가 `resolve`한 `Response` 객체를 전달받을 수 있다.

`Response.prototype`은 다양한 메서드를 제공하는데, `json` 타입의 경우 `Response.prototype.json` 메서드를 사용하여 HTTP 응답 몸체<sup>response body</sup>를 취득하여 역직렬화한다.

```jsx
fetch(`${url}`)
  .then((res) => res.json())
  .then((data) => console.log(data));
```

**fetch 함수가 반환하는 프로미스는 404, 500 등과 같은 에러가 발생해도 에러를 reject하지 않고 불리언 타입의 ok 상태를 false로 설정한 Response 객체를 resolve한다.  
네트워크 장애나 CORS 에러 등에만 프로미스를 reject한다.**

따라서 다음과 같이 에러를 처리한다.

```jsx
fetch(`${url}`)
  .then((res) => {
    if (!res.ok) throw new Error(res.statusText);
    return res.json();
  })
  .then((todo) => console.log(todo))
  .catch((err) => console.error(err));
```

`axios`는 모든 HTTP 에러를 `reject`하는 프로미스를 반환하므로 `catch`에서 모든 에러를 처리할 수 있다.

`fetch` 함수에 대한 더 자세한 내용은 MDN의 ['Using Fetch'](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) 페이지를 참고하자.
